apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakEyTURNdwpNakEwTXpCYUZ3MDBNakEyTURNd01qQTBNekJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEU0xhL1FmYUQ0aVVjeGY0Uno4OHltczVpOXBVOUdPR2xuNjhweEc0dDUzZVp6WklUTwpqcmo0a1hnVXV3S1NzS3NYeTZuejJjWXBObTJDcW1LQkt6TDdwNmQ3V3ZVb1JMYlRRV1IyenJ2NzAwWDdKMjNECk5wclpud3V4UGtnZ3ZrdzhuVldlQ2FkQTlmNmJGT3EwenFzbjBkUkxPL0VCeXpSL29jWDlqS2U2dHdyaWRYUmEKeGRlUERZUG9haWhrNEM0UE4rWlJsM2R2K2Z5QjhkNGNYOEV4d0NjZ3R6Y1VCVjF4YjRNbnlRd0Y3ZU5kOEhlWAp2cXFmM1hxY2lJRlpZL1RPdTBkU3dSYXp5eHVHMHlhOTFYRW4vbnZBMkxSRnplTlplUkZKbCtoZWJjaUhKdmE3CmQ3MWJ3ZHRSM1N2U0NNYlcxVHh5MUh5OXM3TXNCWk40bWR1UkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFyWVN1MlloeVJVZ0h0TnpIcwpKVUx2RFdGTi9qQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFkclFMUy9VNlRsRWx3MXdCc1Y5VXpXWnloSUZUCnVtSmpsNFphRUVNODd1WUFJbU1KYnUyeEljZmhuR3Y5b0NiUEM0VjdYY1h4MFFReUpvUklTZXN5c2ZYN0VoVDYKNmoxa1VOTGd6TEhYMzFYT014eXRCbHlsSkYvOGpiblh0Z3QwT2tMWlZoRHZYN0tMQ0xzdWpXc0d4R0l1c3dlRApKSklqenNMMlRIS3Rhdjl5blc0emNNdDhWbEtxZy9rNmY3bmtFYnBta3JqeVR4R0ZUTVNKQlBpRkRhajd3Zm8zCkRETlloRUYvb1ljQjhjSG4waG9mNUV0cmhHSDFzSEJBU2FZNGJ3R3dCZU5oNUJBMnYrYUZRU1d1aXFVM2NPTGkKSDh0dVZ1SjAwOU1wS3RPekc2cllHcUd1QStWblhSNkttcVBLdnkxWWdWRm1NVEdXM2lGOFVDd05nZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://70b6405c-13d7-4deb-8826-289d47357a73.k8s.ondigitalocean.com
  name: do-sgp1-k8s-1-22-8-do-1-sgp1-1654221900239
contexts:
- context:
    cluster: do-sgp1-k8s-1-22-8-do-1-sgp1-1654221900239
    user: do-sgp1-k8s-1-22-8-do-1-sgp1-1654221900239-admin
  name: do-sgp1-k8s-1-22-8-do-1-sgp1-1654221900239
current-context: do-sgp1-k8s-1-22-8-do-1-sgp1-1654221900239
kind: Config
preferences: {}
users:
- name: do-sgp1-k8s-1-22-8-do-1-sgp1-1654221900239-admin
  user:
    token: dop_v1_5b7e504245894acbeee4539d514c95b3d6af45fb1f62d83f5f9084ba71c3c9ce
